### PR TITLE
Feature/GitHub actions

### PR DESCRIPTION
**Pull request by FrancescoTekapp**
Hello @osalvador, 

Yesterday I missed this statement inside CI

```
build-args: REPLICADB_RELEASE_VERSION=${{ env.version }}
```
to pass as an argument the value of ReplicaDB version.

### CODE REVIEW

**Comment by FrancescoTekapp** [comment]
Hello @osalvador,

thanks for the merge. 
I was wrong, We need also to update the Dockerfile to download the version built previously, replacing this line
https://github.com/osalvador/ReplicaDB/blob/36827e64936b2d07985af8d2d3cd8deee75bbcad/Dockerfile#L14

 with 

```
RUN wget https://github.com/osalvador/ReplicaDB/releases/download/v${REPLICADB_VERSION}/ReplicaDB-${REPLICADB_VERSION}.tar.gz 
```

Do I need to open a PR or do You prefer to modify directly the file?

**Comment by osalvador** [comment]
Hi @FrancescoTekapp,

It's better to use the local packaged version, I've fixed the bug with the version name in the Dockerfile and Containerfile.

**Comment by FrancescoTekapp** [comment]
Hello @osalvador,

Great, I agree with You. Thanks for your help!
If you agree I will add a PR to edit the README in Docker section adding a short explanation for the images and Podman support.

**Comment by osalvador** [comment]
Of course, perfect! Thank you!

**Pull request merged**
