### PR TITLE
fix empty "WHEN MATCHED THEN UPDATE SET" clause on "MERGE INTO"

### PR DESCRIPTION
**Pull request by qrollin**
See our conversation on https://github.com/osalvador/ReplicaDB/issues/96

The stream is just a different way to do the filter and append of columns, the main part being the finishing `if` conditionally adding the `WHEN MATCHED THEN UPDATE SET` if there is any column to update.

### CODE REVIEW

**Comment by qrollin** [comment]
I implemented this solution only for SQLServerManager because it is my current concern, but similar behavior can be observed for OracleManager, StandardJDBCManager and OracleManagerCDC.

**Comment by osalvador** [comment]
Hi @qrollin,

Great contribution, thank you very much. Now I understand what you want to do.

However, there is one thing that worries me because this change will cause some source rows in the sink to be ignored, it is true that they will be the ones that may give an error in the merge statement. For the time, an alert will have to be included to indicate this. 

Thank you again!

**Comment by qrollin** [comment]
I'm not sure I quite understand what you mean by :

>  some source rows in the sink to be ignored

because this should only prevent syntax error on the `MERGE INTO` query generation, in the specific case where the all the source table columns are part of the PK.
Therefore, it should be equivalent to a clause `WHEN MATCHED DO NOTHING`, so no error raised on merged rows if the PK already exists

**Comment by osalvador** [comment]
Hi @qrollin,

That is, there are rows that in case of a match will be ignored. This means that we have moved records around the network from source to sink that are not going to persist in the sink. For the time, I will leave a warning in the log. 

Thank you very much.

**Pull request merged**
